# Generated by Django 4.2.30 on 2026-08-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phd_reading_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readingitem",
            name="subtitle",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="readingitem",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
